imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MRMainBundle/Resources/config/services.yml" }
    - { resource: "@MRBackOfficeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MR\MainBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: FOS\UserBundle\Form\Type\RegistrationFormType
            name: fos_user_registration_form
            validation_groups: [Registration, Default]
        confirmation:
            enabled: true
            template: '@FOSUser/Registration/email.txt.twig'
    profile:
        form:
            type: FOS\UserBundle\Form\Type\ProfileFormType
            #validation_groups: [Profile, Default]
    resetting:
        email:
            template: '@FOSUser/Resetting/email.txt.twig'
    group:
        group_class: MR\MainBundle\Entity\Group
    from_email:
        address: mail@domain.tld
        sender_name: user

easy_admin:
    site_name: My<i>Rabbit</i>
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'   
    entities:
        Lapin:
            class: MR\BackOfficeBundle\Entity\Lapin
            label: 'Lapin'
            list:
                title: "Liste des races de lapins" 
                fields:
                    - numero
                    - date_naissance
                    - couleur
                    - race
                    - sexe
                    - { property: 'sexe', type: 'boolean' }                
            form:
                fields:
                    - numero
                    - date_naissance
                    - couleur
                    - race
                    - sexe
                    - { property: 'sexe', type: 'choice',type_options: {choices: {'Male':'1', 'Female':'0'}} }
            new:
                fields:
                    - { property: 'sexe', type_options: { required: true } }
                title:  'Ajout Lapin'
            edit:
                title:  'Modification Informations Lapin'                
                    
        Engraissement:
            class: MR\BackOfficeBundle\Entity\Engraissement 
            label: 'Engraissement'
            
        MiseBas:
            class: MR\BackOfficeBundle\Entity\MiseBas
            label: 'Mise Bas'
            list:
                title: "Liste des cages"  
            form:
                fields:
                    - date_mise_bas
                    - nombre_vivants
                    - nombre_morts
                    - nombre_adoptes
                    - nombre_rejetes
                    - { property: 'lapin', type: 'easyadmin_autocomplete', type_options: { class: 'MR\BackOfficeBundle\Entity\Lapin' } }
        Saillie:
            class: MR\BackOfficeBundle\Entity\Saillie
            label: 'Saillie'
            list:
                title: "Liste  des saillies"  
            form:
                fields:
                    - femelle
                    - male
                    - palpation
                    - { property: 'palpation', type: 'choice',type_options: {choices: {'Succés':'1', 'Echec':'0'}} }
                    - date_saillie
            new:
                fields:
                    - { property: 'femelle', type_options: { required: true } } 
                    - { property: 'male', type_options: { required: true } } 
                    - { property: 'palpation', type_options: { required: true } }
        Servage:
            class: MR\BackOfficeBundle\Entity\Servage
            label: 'Sevrage'
            list:
                title: "Liste  des Sevrage"
            form:
                fields:
                    - date_servage
                    - nbr_lapereaux
                    - poids_totale
                    - femelle
            new:
                fields:
                    - { property: 'femelle', type_options: { required: false } } 